Add additional data into config file
acmutd/hackportal pull request #129
Opened 2022-05-29 21:12 UTC by DedsecKnight

Resolves #127 

Data added into config file: 
- Sponsors
- Team Member
- Keynote Speakers
- FAQ
- Footer Data

2022-06-21 02:14 UTC, NickBurnett submitted a review, later dismissed
looks pretty good

2022-06-21 02:14 UTC, NickBurnett commented on components/KeynoteSpeaker.tsx
> +        // style={{ backgroundColor: props.cardColor.light, overflow: 'hidden' }}
Can we remove this comment?

2022-07-14 01:20 UTC, nam-t24 commented
I believe this takes care of the rest of the configurable class colors. We should probably review this pr and merge if it's good soon so that other branches can start utilizing the config colors

2022-07-17 02:17 UTC, abdullah50053 submitted a review, later dismissed

2023-01-18 17:02 UTC, MichaelZhao21 requested changes
Hi! This is rly rly good; there's just a few small changes to make :33 

Something funny look at the notes I made reading through the code:
```
primary: #F2F3FF or bg-indigo-100 or #ECEEFF
primaryDark: #C1C8FF or #DCDEFF or #D0D5FF or indigo-500
secondary: #D8F8FF or aqua
secondaryDark: #B0F1FF or darkAqua
complementary: #FDECFF or purple-200
complementaryDark: #F8ACFF or red-300
```

2023-01-18 17:08 UTC, NickBurnett submitted a review, later dismissed
Everything Michael said

2023-01-25 04:37 UTC, MichaelZhao21 commented on components/PendingQuestion.tsx
>          <circle cx="7" cy="7" r="5" fill="#F8ACFF" />
update tailwind is a bitch so u have to do this:
```html
      <svg height="14" width="14" className="fill-current text-complementaryDark">
        {/* !change bullet color */}
        <circle cx="7" cy="7" r="5" />
      </svg>
```

2023-01-25 04:40 UTC, MichaelZhao21 submitted a review, later dismissed

2023-01-25 19:08 UTC, MichaelZhao21 approved these changes
lgtm!

2023-02-12 10:20 UTC, MichaelZhao21 requested changes
Ah so apparently there's a bunch of things in here that we _don't_ want in the config file??? (@abdullah50053 confirm)

2023-02-13 05:22 UTC, abdullah50053 commented
> Ah so apparently there's a bunch of things in here that we _don't_ want in the config file??? (@abdullah50053 confirm)
@MichaelZhao21:
That's correct, a lot of the things in here we're keeping in the DB. We need to keep the color and event config stuff and bin everything else

2023-02-14 16:15 UTC, MichaelZhao21 commented
I resolved all merge conflicts with develop, but I don't have the brain cells rn to remove everything else from the config file

2023-02-15 22:53 UTC, MichaelZhao21 commented
@nam-t24 Can we just recreate this PR with only @abdullah50053's wanted changes cause it's so much more painful to remove everything we don't want.

2023-02-16 03:23 UTC, nam-t24 commented
> @nam-t24 Can we just recreate this PR with only @abdullah50053's wanted changes cause it's so much more painful to remove everything we don't want.

yah that'll be good

2023-02-21 16:34 UTC, MichaelZhao21 commented
Irrelevent due to #216

2023-02-21 16:34 UTC, closed without merging