Implemented feature for super admin to CRUD challenges database
acmutd/hackportal pull request #151
Opened 2022-06-28 04:35 UTC by DedsecKnight

resolves #144 

Note: Since this PR is basically copy everything from #138, there are possibly some implementation for event CRUD that I forgot to switch to challenge CRUD.

2022-07-05 04:56 UTC, abdullah50053 commented
Currently no way to remove a prize:
<img width="1422" alt="Screen Shot 2022-07-04 at 11 52 55 PM" src="https://user-images.githubusercontent.com/71054105/177252042-a7674065-777b-46ca-8060-65f6e4386b38.png">

Also should rename to "Save Changes":
<img width="1417" alt="Screen Shot 2022-07-04 at 11 53 14 PM" src="https://user-images.githubusercontent.com/71054105/177252072-ebce8a44-f728-4706-b4fe-c62a8e738e9b.png">

Challenge is spelled incorrectly:
<img width="486" alt="Screen Shot 2022-07-04 at 11 55 22 PM" src="https://user-images.githubusercontent.com/71054105/177252301-d90f5e9d-6551-4e56-a253-e080e02e7caa.png">

2022-07-12 01:02 UTC, abdullah50053 requested changes
Add the ability to adjust the ranking of challenges. This would ideally be done by dragging the cards in the desired ranking order.
![Screen Shot 2022-07-11 at 8 01 29 PM](https://user-images.githubusercontent.com/71054105/178385597-666bab33-ffaf-415c-a531-9ad25e97c5f0.png)

2022-07-23 02:45 UTC, abdullah50053 submitted a review, later dismissed

2022-07-23 19:52 UTC, nam-t24 approved these changes

2022-07-23 23:15 UTC, abdullah50053 approved these changes

2022-07-23 23:15 UTC, merged