feat: Additional QR code feature
acmutd/hackportal pull request #251
Opened 2024-02-22 18:38 UTC by nova44056

- display user name when their qr code is scanned
- add timestamp to backend when qr code is scanned

2024-02-28 05:22 UTC, DedsecKnight requested changes

2024-02-28 05:22 UTC, DedsecKnight commented on pages/admin/scan/index.tsx
> +                          <p>{success ?? 'Unexpected error!'}</p>
I believe this line is duplicated.

2024-02-28 15:05 UTC, uy-seng commented on pages/admin/scan/index.tsx
> +                          <p>{success ?? 'Unexpected error!'}</p>
i removed the duplicated line

2024-02-28 17:09 UTC, DedsecKnight approved these changes
LGTM :+1:

2024-03-07 06:14 UTC, raywa04 approved these changes
changes seem good to me :)

2024-03-07 21:19 UTC, merged