feat(profile): Updated profile page
acmutd/hackportal pull request #278
Opened 2024-06-30 09:38 UTC by vvyn

Changed profile page ui

2024-06-30 20:17 UTC, DedsecKnight requested changes

2024-06-30 20:17 UTC, DedsecKnight commented on pages/profile.tsx
>              />
Can we specify hacker's group here as well?

2024-07-01 05:12 UTC, DedsecKnight requested changes

2024-07-01 05:12 UTC, DedsecKnight commented on pages/profile.tsx
> +  console.log(profile);
Remove this.

2024-07-01 15:04 UTC, DedsecKnight approved these changes
lgtm :+1:

2024-07-01 17:50 UTC, raywa04 approved these changes
lgtm!

2024-07-01 18:37 UTC, merged