Implement about page
acmutd/hackportal pull request #40
Opened 2021-10-24 03:32 UTC by DedsecKnight

### Changes made in this PR: 
- [x] Basic implementation of About section based on Figma design.
- [x] Add more color variation to "My Answered Question" section.
- [x] Implement member cards for "Meet Our Team".
- [x] Implement "Expand all" feature of FAQ
- [x] Resolve issues regarding hardcoded data.
- [x] Add documentation for Prop types.
- [x] Resolve conflict with #38.
- [x] Add generic description for Hackathon introduction.
- [x] Implement backend for About section.
- [x] Determine how data will be stored in the backend as of now, fake data is used to populate the front-end.
- [x] Integrate Next.js' Data-Fetching features to optimize process of fetching data from backend.
- [x] Implement Error Handling for form submission in `/about/questions`.

2021-10-29 19:33 UTC, abdullah50053 submitted a review, later dismissed
Vercel-specific issues will be identified by @WillieCubed 
Everything else looks good.

2021-11-06 03:47 UTC, WillieCubed requested changes
This is incredibly Gucci!

For a future release, I will recommend updating the answered questions in realtime by using the relevant Cloud Firestore API or telling the user that they will have to refresh to see the answered questions. However, the only major change to make is showing the expanded answered questions by default as it's not clear to the user they need to click on the answers to expand them as that's an important part of UX that will likely get overlooked by the user.

2021-11-06 04:36 UTC, WillieCubed approved these changes
LGTM!

2021-11-06 04:52 UTC, abdullah50053 approved these changes

2021-11-06 04:52 UTC, merged