feat: Implement dashboard, keynote speakers, nav bar effects
acmutd/hackportal pull request #55
Opened 2022-01-11 16:38 UTC by nam-t24

-All additions from dashboard has been added.
-Keynote section added to home page with keynote information fetched from firebase.
-Spotlight events added to hack center with event data fetched from database and displayed if current date and time is within the date and time given from the event data. Events are displayed in a carousel from Swiper JS library. 
-Added mobile nav bar effects: icon changes to make opening and closing more intuitive, hover effects over link to make it more clear on where the user is hovering

2022-01-11 21:14 UTC, abdullah50053 requested changes
<img width="743" alt="Screen Shot 2022-01-11 at 2 57 23 PM" src="https://user-images.githubusercontent.com/71054105/149020431-4697ecfc-78c1-4890-b766-52cc89fefb0d.png">
Change visual for no spotlighted events - replace with announcements for this PR

Replace the "Your Team" section with dynamic "Challenge" cards (in a separate PR)

2022-01-12 01:38 UTC, WillieCubed commented
#### 📝 Changed routes:


| [**…ard/Components/Sidebar**](https://hackportal-do96rs388-acmutd.vercel.app/dashboard/Components/Sidebar) | [**…mponents/SpotlightCard**](https://hackportal-do96rs388-acmutd.vercel.app/dashboard/Components/SpotlightCard) |
|:-:|:-:|
|<a href="https://hackportal-do96rs388-acmutd.vercel.app/dashboard/Components/Sidebar"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/WMYTsRb2P_oNA_HWJsFfM3QVgPO2YpqiAmzV-13Bp-JswPNf3s-LXTx5Xf11afqGrVjfVXP5hujT0h-NF-F3aA.png&w=600" alt="Screenshot of /dashboard/Components/Sidebar" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/sJ02lw0ck84N5bZ41cKSWZ3M78YOnhPrRQsNjc-KslU7Jumlf7a-A5H1moMWtarNX7SILW-P0VuZi0vVxve3hA.png">(view full size)</a> |<a href="https://hackportal-do96rs388-acmutd.vercel.app/dashboard/Components/SpotlightCard"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/t4oArWuHc_849CJs45RgMuwAH6U2k1IuCEoFZcqjYAh1Ctnbp3o3bGwrTNUJuXrSo6oMkC_Uudjae9w10lmTGw.png&w=600" alt="Screenshot of /dashboard/Components/SpotlightCard" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/tXCS6oBx107a4mQbvdpVXcLsC33N4EVsIQRO7yU2F5-MbhHHvFA0QT896OXsMGF1l99lq2ImGh01HnEreCCYkQ.png">(view full size)</a> |



| [**…ts/SpotlightCardScroll**](https://hackportal-do96rs388-acmutd.vercel.app/dashboard/Components/SpotlightCardScroll) | [**/dashboard**](https://hackportal-do96rs388-acmutd.vercel.app/dashboard) |
|:-:|:-:|
|<a href="https://hackportal-do96rs388-acmutd.vercel.app/dashboard/Components/SpotlightCardScroll"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/tf80a-vEhy6MeLGMImjHIGGJoV7w3oJneRbTeLH_92DSCKIrzA4foPWQqN2afdj5hbycIcnj1vqzDTYMJ3082Q.png&w=600" alt="Screenshot of /dashboard/Components/SpotlightCardScroll" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/eupmj4WMcFrsciEbguMiQrb57rt4d6s2p5L7ymPBNq7TbJ1Z0R1Y3apNBmKLp399sX1ErYGs6AtSM-fP88YBwg.png">(view full size)</a> |<a href="https://hackportal-do96rs388-acmutd.vercel.app/dashboard"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/XhXpG5AD8jD1b4lww-adYLw1-uKsFeemBY-8xku5LS9dR1YXVYcDhkXR2sw53m_q2yDSyF3Gc9Ey3ZRmb2fD9A.png&w=600" alt="Screenshot of /dashboard" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/aehQsKjKMtchGScRWvh8AuGNu0jY5In4htbBjwauInq6guJKQVe2mXlNLUcuzfkxAgNQg81Wk48DlKmKXAFApA.png">(view full size)</a> |



| [**/dashboard/scan-in**](https://hackportal-do96rs388-acmutd.vercel.app/dashboard/scan-in) | [**/**](https://hackportal-do96rs388-acmutd.vercel.app/) |
|:-:|:-:|
|<a href="https://hackportal-do96rs388-acmutd.vercel.app/dashboard/scan-in"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/XA4cVDu3IwFkbgYvXh0yxWdWY2raLb5ERRmMTpdCnIXhuZne0zyz4GuC1HgGF2LxlH3gTKHVVW7z32KOQ9q3rA.png&w=600" alt="Screenshot of /dashboard/scan-in" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/8DA7vYHWQHKNi0TimUKbimfd1h5eEiPL2qBEHKEFkyhJD2-oCECtktyPF0gTiWLdxLZb8JfQiYGe1FClqiNh1Q.png">(view full size)</a> |<a href="https://hackportal-do96rs388-acmutd.vercel.app/"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/GYjXH6vNOIXfuf1IyS7456V6MHLZCcYX2yYlXza3yjUYyndns1N2rQ5y0Qo_nrdGQvNrSlk65dsmMDVYA3ZjjQ.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/sDOVo83BFoU1dOZKrCX804aKtVgdrrHrhzJBG9Wg1imUpWwG6IWZD2oEzoE8r6P5KHM8NqXxdOvu-6-ufuhToA.png">(view full size)</a> |



And 2 other routes:
- [**/api/keynotespeakers**](https://hackportal-do96rs388-acmutd.vercel.app/api/keynotespeakers)
- [**/api/spotlightevents**](https://hackportal-do96rs388-acmutd.vercel.app/api/spotlightevents)



Commit 3046fd9d7459d532262d0c4d8995d9f6ba589ae4 (https://hackportal-do96rs388-acmutd.vercel.app).

2022-01-12 01:58 UTC, nam-t24 commented
No longer displays spotlight when 0 events are occurring.

2022-01-12 01:59 UTC, abdullah50053 approved these changes

2022-01-12 02:40 UTC, abdullah50053 approved these changes

2022-01-12 02:44 UTC, DedsecKnight approved these changes

2022-01-12 02:44 UTC, merged