feat: Implement Password based Login
acmutd/hackportal pull request #62
Opened 2022-02-02 14:40 UTC by nam-t24

Features Added
- login and signup page
- password based login/signup option
- email verification (requirement before logging in)
- password reset email to user
- browser save account credential and autocomplete
- challenge card masonry layout in hackcenter

2022-02-02 15:32 UTC, abdullah50053 commented
![Screen Shot 2022-02-02 at 9 30 53 AM](https://user-images.githubusercontent.com/71054105/152184842-0c38ecd5-5fd5-4ebf-ba4f-9efee7bb5ae8.png)
Password should not be visible on account creation.

2022-02-02 15:34 UTC, nam-t24 commented
> ![Screen Shot 2022-02-02 at 9 30 53 AM](https://user-images.githubusercontent.com/71054105/152184842-0c38ecd5-5fd5-4ebf-ba4f-9efee7bb5ae8.png)
> Password should not be visible on account creation.

When they create an account shouldn't they know what password they're entering in incase they mistype a character?

2022-02-02 16:00 UTC, nam-t24 commented
I could have the password field have a checkbox to allow the user to mask or unmask the password they are typing. Eliminates the confirm password field for better user experience.

2022-02-02 16:26 UTC, LoganLieou requested changes

2022-02-02 16:26 UTC, LoganLieou commented on pages/auth/index.tsx
> +            <input
type="password"

2022-02-02 22:05 UTC, WillieCubed commented
#### 📝 Changed routes:


| [**/admin**](https://hackportal-svdd5ogvf-acmutd.vercel.app/admin) | [**…n/resolve/\[questionId\]**](https://hackportal-svdd5ogvf-acmutd.vercel.app/admin/resolve/[questionId]) |
|:-:|:-:|
|<a href="https://hackportal-svdd5ogvf-acmutd.vercel.app/admin"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/407L1Vfj3tzA3mp4ngNb9cSPbwU_fkEQPGel0NeBofe_p2r0RJj7bZxla2cD-QNkCxDZPazIydW2xxUFGowzgA.png&w=600" alt="Screenshot of /admin" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/tyKo1fSY1vp-4rIPaCvZ9zE9Kx29KPs-3H8XiQSKS66Mex74IjxYhftjo9zm-K_RCZjNoKiJOyc8FMnDp1vBGg.png">(view full size)</a> |<a href="https://hackportal-svdd5ogvf-acmutd.vercel.app/admin/resolve/[questionId]"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/ot6T2wxZ3hAKeEg9SsHkQ9KEINWLeFL4KJei6phl37nC04RtHj_a0_uzhsnz--T28pDNth4M6ewv6R2qiTnVaw.png&w=600" alt="Screenshot of /admin/resolve/[questionId]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/h38-cI22HJzg-u9XZNdynpTFhKvtTyAUlC_ED8vQcYkxzGEehVBhte6TJ-sWLEENc-vVSASlGivMG-bs7TfgrA.png">(view full size)</a> |



| [**/admin/scan**](https://hackportal-svdd5ogvf-acmutd.vercel.app/admin/scan) | [**/admin/users**](https://hackportal-svdd5ogvf-acmutd.vercel.app/admin/users) |
|:-:|:-:|
|<a href="https://hackportal-svdd5ogvf-acmutd.vercel.app/admin/scan"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/S9UfBM8IOGVzsLRML-ANTLHuA_ePMcLxQglkgdAgzPBhHuQ50z9_6gyw8dl2XqY8hQm73EZ7gaGh3XrlyUaibA.png&w=600" alt="Screenshot of /admin/scan" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/y1hVSF44ldex0wC4t-vRibp_AK25yp_EMwSxE0y51Toy5JpYORpm3vyKX43chWGxtKaD0DdDnuvN6ivm64sgsA.png">(view full size)</a> |<a href="https://hackportal-svdd5ogvf-acmutd.vercel.app/admin/users"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/vnXcljk9FRS3AWFi8EUtDAObzfCAkxcSbH0SfTAGfkVLxuQi87IW7rzKX1XnfzPHXlsOU3iRXA09v-mRzaKbYw.png&w=600" alt="Screenshot of /admin/users" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/nd2IWK-HY2UHtIgQhOXxyezbbCB0cmThcjcd5YC5w7H3ms21NX_FYkb5vkvK6OstfQ6dJo71GTfaXDMZ_O2_NA.png">(view full size)</a> |



| [**/auth**](https://hackportal-svdd5ogvf-acmutd.vercel.app/auth) | [**/auth/signup**](https://hackportal-svdd5ogvf-acmutd.vercel.app/auth/signup) |
|:-:|:-:|
|<a href="https://hackportal-svdd5ogvf-acmutd.vercel.app/auth"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/n0JExHP_8kPh0orRHacKO6_sNRbABW5xZeKwwdcBKbO1OKRnCXikGyuhuHEZRkn4aXCb7ub5MKxh15me3-XeAQ.png&w=600" alt="Screenshot of /auth" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/d1J8CvCuC5QHBXLTpoPfAT_uq0QSd1PDKiO5V21pc9DXYXJtEqSt0R4v4EMxALICT4wulmUBvQfVhzY84wJh1g.png">(view full size)</a> |<a href="https://hackportal-svdd5ogvf-acmutd.vercel.app/auth/signup"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/j_QvSbqTd9St5x300EbencBPTysQu5tEzK9NyvMppQ1f2BdYawixLRAlyMYiHV93918G4PnP3DHjf0KxCRMLrg.png&w=600" alt="Screenshot of /auth/signup" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/AV0kITg15B-MBGnhQ1wMtILf9_UkEVKBITlcFeNlLRMt6yNma1DOTJ6d_i9c4xAMPs1S7fXi7G0x52h2EgmHeQ.png">(view full size)</a> |



And 16 other routes:
- [**/api/applications/\[applicationId\]**](https://hackportal-svdd5ogvf-acmutd.vercel.app/api/applications/[applicationId])
- [**/api/applications**](https://hackportal-svdd5ogvf-acmutd.vercel.app/api/applications)
- [**/api/scan**](https://hackportal-svdd5ogvf-acmutd.vercel.app/api/scan)
- [**/api/scan/create**](https://hackportal-svdd5ogvf-acmutd.vercel.app/api/scan/create)
- [**/api/scan/delete**](https://hackportal-svdd5ogvf-acmutd.vercel.app/api/scan/delete)
- [**/api/scan/update**](https://hackportal-svdd5ogvf-acmutd.vercel.app/api/scan/update)
- [**/api/userinfo**](https://hackportal-svdd5ogvf-acmutd.vercel.app/api/userinfo)
- [**/api/users/roles**](https://hackportal-svdd5ogvf-acmutd.vercel.app/api/users/roles)
- [**/dashboard/Components/ChallengeCard**](https://hackportal-svdd5ogvf-acmutd.vercel.app/dashboard/Components/ChallengeCard)
- [**/dashboard/Components/Sidebar**](https://hackportal-svdd5ogvf-acmutd.vercel.app/dashboard/Components/Sidebar)
- [**/dashboard/hackerpack**](https://hackportal-svdd5ogvf-acmutd.vercel.app/dashboard/hackerpack)
- [**/dashboard**](https://hackportal-svdd5ogvf-acmutd.vercel.app/dashboard)
- [**/dashboard/scan-in**](https://hackportal-svdd5ogvf-acmutd.vercel.app/dashboard/scan-in)
- [**/**](https://hackportal-svdd5ogvf-acmutd.vercel.app/)
- [**/profile**](https://hackportal-svdd5ogvf-acmutd.vercel.app/profile)
- [**/register**](https://hackportal-svdd5ogvf-acmutd.vercel.app/register)



Commit 95312bd9a42ee8438e9ff76cf51cea0244b5cad0 (https://hackportal-svdd5ogvf-acmutd.vercel.app).

2022-02-02 22:23 UTC, abdullah50053 commented
Need merge conflicts resolved @nam-t24

2022-02-03 01:27 UTC, abdullah50053 approved these changes

2022-02-05 17:43 UTC, DedsecKnight approved these changes

2022-02-05 18:02 UTC, merged